/**
 * Cardcom API v11 client — LowProfile hosted checkout + token-based
 * recurring charges.
 *
 * Field names verified against Cardcom's own published OpenAPI spec
 * (https://github.com/MosheRivkin/cardcom-ts-sdk/blob/master/data/swagger.json,
 * generated by NSwag from Cardcom's live https://secure.cardcom.solutions/
 * service — this replaces an earlier version of this file written without
 * access to any spec). Two things that earlier version got wrong were not
 * cosmetic:
 *   - LowProfileResult (the response getLowProfileResult reads) has no
 *     top-level DealResponse or Amount field at all — the per-charge outcome
 *     lives in its nested TranzactionInfo (itself a full TransactionInfo,
 *     with its own ResponseCode/Amount). Checking a field that doesn't
 *     exist meant `paid` was always false, so a genuinely successful
 *     Cardcom charge would have been recorded as failed by our own webhook.
 *   - Transactions/Transaction (chargeToken) takes a flat `Token` string,
 *     not `TokenToCharge: { Token }` — the nested shape doesn't exist in
 *     the schema at all, so a recurring charge would never have actually
 *     charged the saved card.
 * ApiName + TerminalNumber authenticate every call below; none of
 * LowProfile/Create, LowProfile/GetLpResult or Transactions/Transaction
 * take an ApiPassword in Cardcom's schema (it's additionalProperties:false
 * on all three) — CARDCOM_API_PASSWORD is intentionally unused here.
 */

const CARDCOM_BASE_URL = "https://secure.cardcom.solutions/api/v11";

function requiredEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is not configured`);
  return value;
}

export interface CardcomDocumentInput {
  /** Buyer name as it should appear on the tax invoice. */
  name: string;
  email?: string;
  /** Israeli ח.פ / ת.ז, if known — not required to issue a receipt. */
  taxId?: string;
  productDescription: string;
}

export interface CreateLowProfileInput {
  /** Amount to actually charge right now — 0 for a trial signup (see tokenOnly). */
  amountIls: number;
  productName: string;
  /** Our billing_checkouts.id — round-tripped by Cardcom so the webhook can match the callback to a row without trusting anything else in the payload. */
  returnValue: string;
  successRedirectUrl: string;
  failedRedirectUrl: string;
  webhookUrl: string;
  /** Also save a reusable card token for recurring monthly billing. */
  createToken: boolean;
  /** Free-trial signups: save the card via Cardcom's token-only operation without charging anything now — the recurring cron makes the real first charge when the trial ends. */
  tokenOnly?: boolean;
  /** Omitted for a tokenOnly checkout — nothing was actually paid yet, so there's nothing to invoice. */
  document?: CardcomDocumentInput;
}

export interface CreateLowProfileResult {
  ok: boolean;
  description: string;
  lowProfileId?: string;
  redirectUrl?: string;
}

/** Step 1: ask Cardcom for a hosted checkout page URL. */
export async function createLowProfile(input: CreateLowProfileInput): Promise<CreateLowProfileResult> {
  const terminalNumber = Number(requiredEnv("CARDCOM_TERMINAL_NUMBER"));
  const apiName = requiredEnv("CARDCOM_API_NAME");

  const res = await fetch(`${CARDCOM_BASE_URL}/LowProfile/Create`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      TerminalNumber: terminalNumber,
      ApiName: apiName,
      Operation: input.tokenOnly ? "CreateTokenOnly" : input.createToken ? "ChargeAndCreateToken" : "ChargeOnly",
      Amount: input.amountIls,
      ProductName: input.productName,
      ReturnValue: input.returnValue,
      SuccessRedirectUrl: input.successRedirectUrl,
      FailedRedirectUrl: input.failedRedirectUrl,
      WebHookUrl: input.webhookUrl,
      ...(input.document
        ? {
            Document: {
              DocumentTypeToCreate: "TaxInvoiceAndReceipt",
              Name: input.document.name,
              Email: input.document.email,
              TaxId: input.document.taxId,
              IsSendByEmail: Boolean(input.document.email),
              Products: [
                {
                  Description: input.document.productDescription,
                  UnitCost: input.amountIls,
                  Quantity: 1,
                },
              ],
            },
          }
        : {}),
    }),
  });

  const body = (await res.json()) as {
    ResponseCode: number;
    Description: string;
    LowProfileId?: string;
    Url?: string;
  };

  return {
    ok: body.ResponseCode === 0,
    description: body.Description,
    lowProfileId: body.LowProfileId,
    redirectUrl: body.Url,
  };
}

export interface LowProfileResult {
  ok: boolean;
  description: string;
  /** True only when Cardcom's own record of this LowProfileId shows a completed, successful charge. */
  paid: boolean;
  returnValue?: string;
  amountIls?: number;
  transactionId?: string;
  token?: string;
  tokenExpiry?: string;
  documentNumber?: string;
  documentUrl?: string;
}

/**
 * Step 2 (the security-critical call): look up a LowProfileId's real,
 * server-confirmed status directly from Cardcom using OUR OWN credentials —
 * never trust the webhook POST body itself for the payment decision, only
 * use it to learn which LowProfileId to look up.
 */
export async function getLowProfileResult(lowProfileId: string): Promise<LowProfileResult> {
  const terminalNumber = Number(requiredEnv("CARDCOM_TERMINAL_NUMBER"));
  const apiName = requiredEnv("CARDCOM_API_NAME");

  const res = await fetch(`${CARDCOM_BASE_URL}/LowProfile/GetLpResult`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      TerminalNumber: terminalNumber,
      ApiName: apiName,
      LowProfileId: lowProfileId,
    }),
  });

  const body = (await res.json()) as {
    ResponseCode: number;
    Description: string;
    ReturnValue?: string;
    // Only populated for operations ChargeOnly/ChargeAndCreateToken — a
    // full TransactionInfo, not a flag. Its own ResponseCode (0, or 700/701
    // for a J2/J5 deferred-capture deal) is the real "was this charged"
    // signal; LowProfileResult itself has no such field.
    TranzactionInfo?: { ResponseCode: number; Amount?: number; TranzactionId?: number };
    // Only populated for operations ChargeAndCreateToken/CreateTokenOnly.
    TokenInfo?: { Token?: string; CardMonth?: number; CardYear?: number };
    DocumentInfo?: { DocumentNumber?: number; DocumentUrl?: string };
  };

  const chargeOk = body.TranzactionInfo ? [0, 700, 701].includes(body.TranzactionInfo.ResponseCode) : false;

  return {
    ok: body.ResponseCode === 0,
    description: body.Description,
    paid: body.ResponseCode === 0 && chargeOk,
    returnValue: body.ReturnValue,
    amountIls: body.TranzactionInfo?.Amount,
    transactionId:
      body.TranzactionInfo?.TranzactionId !== undefined ? String(body.TranzactionInfo.TranzactionId) : undefined,
    token: body.TokenInfo?.Token,
    tokenExpiry:
      body.TokenInfo?.CardMonth && body.TokenInfo?.CardYear
        ? `${String(body.TokenInfo.CardMonth).padStart(2, "0")}/${body.TokenInfo.CardYear}`
        : undefined,
    documentNumber: body.DocumentInfo?.DocumentNumber !== undefined ? String(body.DocumentInfo.DocumentNumber) : undefined,
    documentUrl: body.DocumentInfo?.DocumentUrl,
  };
}

export interface ChargeTokenInput {
  token: string;
  /** "MM/YYYY" as stored on billing_subscriptions.cardcom_token_expiry (built from TokenInfo at checkout time) — converted to Cardcom's MMYY below. Omitted from the request if not on file, since it's optional in the schema. */
  cardExpiryMmYyyy?: string | null;
  amountIls: number;
  document: CardcomDocumentInput;
}

export interface ChargeTokenResult {
  ok: boolean;
  description: string;
  transactionId?: string;
  documentNumber?: string;
  documentUrl?: string;
}

/** Recurring monthly charge against a previously saved token (src/app/api/cron/charge-recurring-subscriptions). */
export async function chargeToken(input: ChargeTokenInput): Promise<ChargeTokenResult> {
  const terminalNumber = Number(requiredEnv("CARDCOM_TERMINAL_NUMBER"));
  const apiName = requiredEnv("CARDCOM_API_NAME");

  const [month, year] = input.cardExpiryMmYyyy?.split("/") ?? [];
  const cardExpirationMmYy = month && year ? `${month.padStart(2, "0")}${year.slice(-2)}` : undefined;

  const res = await fetch(`${CARDCOM_BASE_URL}/Transactions/Transaction`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      TerminalNumber: terminalNumber,
      ApiName: apiName,
      Token: input.token,
      ...(cardExpirationMmYy ? { CardExpirationMMYY: cardExpirationMmYy } : {}),
      Amount: input.amountIls,
      Document: {
        DocumentTypeToCreate: "TaxInvoiceAndReceipt",
        Name: input.document.name,
        Email: input.document.email,
        TaxId: input.document.taxId,
        IsSendByEmail: Boolean(input.document.email),
        Products: [
          {
            Description: input.document.productDescription,
            UnitCost: input.amountIls,
            Quantity: 1,
          },
        ],
      },
    }),
  });

  // The response IS a TransactionInfo, flat — unlike LowProfileResult, there's
  // no separate DocumentInfo wrapper; DocumentNumber/DocumentUrl are its own
  // top-level fields.
  const body = (await res.json()) as {
    ResponseCode: number;
    Description: string;
    TranzactionId?: number;
    DocumentNumber?: number;
    DocumentUrl?: string;
  };

  return {
    ok: body.ResponseCode === 0 || body.ResponseCode === 700 || body.ResponseCode === 701,
    description: body.Description,
    transactionId: body.TranzactionId !== undefined ? String(body.TranzactionId) : undefined,
    documentNumber: body.DocumentNumber !== undefined ? String(body.DocumentNumber) : undefined,
    documentUrl: body.DocumentUrl,
  };
}
